### ISSUE TITLE
Code review for the initial commit

### ISSUE THREAD

**Issue by sersut** [chef/chef-acceptance#1]
I think this looks great @patrick-wright. 

The only thing I would do is to have a way to normalize and merge the config and cli options. Here is what I am thinking we can do in cli to make it a bit more generic:

```
# We follow the attr_accessor model elsewhere in chef. This helps us identify where we are 
# setting the value of something against where it is read. 

def attr_accessor :config

def get_option_value(option)
  config[option] || options[option]
end

def verify
  ...
  env_vars << "CHANNEL=#{get_option_value(channel)}"
  ...
end
```

Otherwise it is all good.

**Comment by patrick-wright** [comment]
This code has been refactored and no longer uses a config object
