### ISSUE TITLE
allow the acceptance root for runtime/tmp data to be relocated

### ISSUE THREAD

**Issue by schisamo** [chef/chef-acceptance#36]
I was looking into archiving log output when chef-acceptance suites are executed in a Jenkins job. I noticed temporary, log and auto generated data is being written into the package install tree...namely at:
```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.36/acceptance/.acceptance_logs
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.36/acceptance/*/.acceptance/acceptance-cookbook/tmp/
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.36/acceptance/*/.acceptance/acceptance-cookbook/nodes/
```

It would be best for the root location of these paths to be re-locatable, in this case into the Jenkins workspace for the executing job. It's an anti pattern to write temporary files into the install tree of a package. On some platforms it can make remove/upgrade of a package impossible.

/cc @patrick-wright @sersut @danielsdeleo @tyler-ball

**Comment by sersut** [comment]
👍
